[build]
builder = "DOCKERFILE"
dockerfilePath = "server/Dockerfile"

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
