[build]
builder = "nixpacks"
buildCommand = "cd server && npm install"

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
